### ISSUE TITLE
There is a syntax error in the following Vagrantfile.

### ISSUE THREAD

**Issue by jfranciscos4** [deivisondfs2/machine-basic-packer-vagrant-puppet#1]
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfil
here is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/jfsi/workspace/github/machine-basic-packer-vagrant-puppet/Vagrantfile:5: invalid multibyte char (US-ASCII)
/home/jfsi/workspace/github/machine-basic-packer-vagrant-puppet/Vagrantfile:5: invalid multibyte char (US-ASCII)
/home/jfsi/workspace/github/machine-basic-packer-vagrant-puppet/Vagrantfile:5: syntax error, unexpected $end, expecting keyword_end
  raise "É necessário instalar o plugi...

**Comment by deivisondfs2** [comment]
Encontrado neste link:

http://stackoverflow.com/questions/1739836/invalid-multibyte-char-us-ascii-with-rails-and-ruby-1-9?answertab=votes#tab-top
